apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appstudio-pipelines-runner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appstudio-pipelines-runner
subjects:
- kind: ServiceAccount
  name: konflux-ci-sa
  namespace: konflux-ci
