apiVersion: kueue.x-k8s.io/v1beta1
kind: AdmissionCheck
metadata:
  name: static-admission
spec:
  controllerName: konflux-ci.dev/kueue-external-admission
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-pipeline-queue
spec:
  admissionChecks:
  - static-admission
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: Never
    reclaimWithinCohort: Never
    withinClusterQueue: Never
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - tekton.dev/pipelineruns
    - cpu
    - memory
    - aws-ip
    flavors:
    - name: default-flavor
      resources:
      - name: tekton.dev/pipelineruns
        nominalQuota: '500'
      - name: cpu
        nominalQuota: 1k
      - name: memory
        nominalQuota: 500Ti
      - name: aws-ip
        nominalQuota: '250'
  stopPolicy: None
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default-flavor
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: platform-group-1
spec: {}
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: platform-group-2
spec: {}
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: platform-group-3
spec: {}
