apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- sandbox-sre-member.yaml
- ../../user-management/staging/generated-manifests/member
patches:
  - path: patch_resources.yaml
  - patch: |
      $patch: delete
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: appstudio-pipelines-runner