apiVersion: v1
kind: ServiceAccount
metadata:
  name: konflux-integration-runner
  namespace: build-templates-e2e
secrets:
  - name: quay-push-secret
  - name: registry-redhat-io-pull-secret
imagePullSecrets:
  - name: quay-push-secret
  - name: registry-redhat-io-pull-secret
