apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/external-secrets
  - rbac
  - https://github.com/redhat-appstudio/application-service/config/prometheus/?ref=f50e3eecf84043f0db1f578e0fb93975311f3763


configMapGenerator:
  - literals:
      - GITHUB_ORG="redhat-appstudio-appdata-staging"
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="staging"
    name: feature-flag-config
    behavior: replace

namespace: application-service
