apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/image-controller/config/default?ref=e8bf77dbad674d81c140d16335a834c3a7500e86
images:
  - name: quay.io/konflux-ci/image-controller
    newName: quay.io/redhat-user-workloads/rhtap-build-tenant/image-controller/image-controller
    newTag: on-pr-e8bf77dbad674d81c140d16335a834c3a7500e86
namespace: image-controller
patches:
  - path: ./manager_resources_patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: sealights-token-patch.yaml
