apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/tisutisu/image-controller/config/default?ref=3b64782f8ce40f8d173dc435d41a054c33b10ed7
images:
  - name: quay.io/konflux-ci/image-controller
    newName: registry.build03.ci.openshift.org/ci-op-rftvs1m2/pipeline
    newTag: redhat-appstudio-image-controller-image
namespace: image-controller
patches:
  - path: ./manager_resources_patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
