apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../base
- https://github.com/konflux-ci/image-rbac-proxy/deploy/development/base?ref=6cc5312cd5e347f962b21c86a578ffea54c60e57
# Enable this to create/rotate oauth secret
- ../base/oauth

images:
- name: quay.io/konflux-ci/image-rbac-proxy
  newName: quay.io/konflux-ci/image-rbac-proxy
  newTag: 6cc5312cd5e347f962b21c86a578ffea54c60e57
