apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../base
- https://github.com/konflux-ci/image-rbac-proxy/deploy/development/base?ref=403ef27eb02e7d2ee8fbd0e9db5a359bf83a230f
# Enable this to create/rotate oauth secret
- ../base/oauth

images:
- name: quay.io/konflux-ci/image-rbac-proxy
  newName: quay.io/konflux-ci/image-rbac-proxy
  newTag: 403ef27eb02e7d2ee8fbd0e9db5a359bf83a230f
- name: memcached
  newName: quay.io/kubearchive/memcached
  newTag: 1.6.39
