apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../base
- https://github.com/konflux-ci/image-rbac-proxy/deploy/development/base?ref=1a2c92c702e6fc8b9a6b72f664c04eca5e78df0e
# Enable this to create/rotate oauth secret
- ../base/oauth

images:
- name: quay.io/konflux-ci/image-rbac-proxy
  newName: quay.io/konflux-ci/image-rbac-proxy
  newTag: 1a2c92c702e6fc8b9a6b72f664c04eca5e78df0e
- name: memcached
  newName: quay.io/kubearchive/memcached
  newTag: 1.6.39
