---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/external-secrets

namespace: konflux-kite

images:
  - name: quay.io/konflux-ci/kite-prod
    newTag: cf89c466d8244b4c0e0ddb3acb7e3578784ccedb

  - name: quay.io/konflux-ci/kite-init
    newTag: cf89c466d8244b4c0e0ddb3acb7e3578784ccedb
