---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-integration-service-production-update-2024_06_03__09_34_51-tknc
