---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-KAR-671_stale_ingester_pod_on_kflux-rhel-p01-apgn
