---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-release-service-production-update-2025_07_28__07_23_14-bggy
