---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-itn-2025-00225-02-iztd
