---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-revert-6510-SRVKP-7586-update-pipelines-component-staging-rqhi
