---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/redhat-appstudio-qe/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-KAR-679_stone-stg-rh01_ingester_readiness_probe_failed-wlxf
