apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - ./rbac
  - https://github.com/NigelByrne1/application-service/config/default?ref=966cdc9bfa344dad261140222510ea73f9d85e59
components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: registry.build09.ci.openshift.org/ci-op-xgqjch18/pipeline
    newTag: redhat-appstudio-has-image
configMapGenerator:
  - literals:
      - GITHUB_ORG=redhat-appstudio-qe
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace
namespace: application-service
