apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - ./rbac
  - https://github.com/NigelByrne1/application-service/config/default?ref=3e94d42fb9a0e2654b2b4768a58b237d3235bab0
components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: registry.build09.ci.openshift.org/ci-op-xi27j8qn/pipeline
    newTag: redhat-appstudio-has-image
configMapGenerator:
  - literals:
      - GITHUB_ORG=redhat-appstudio-qe
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace
namespace: application-service
