apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - ./rbac
  - https://github.com/redhat-appstudio/application-service/config/default?ref=f50e3eecf84043f0db1f578e0fb93975311f3763


components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling

images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/redhat-appstudio/application-service
    newTag: f50e3eecf84043f0db1f578e0fb93975311f3763

configMapGenerator:
  - literals:
      - GITHUB_ORG=""
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace


namespace: application-service
