apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: SpaceProvisionerConfig
metadata:
  name: member-kflux-ocp-p01.7ayg.p1.openshiftapps.com
  namespace: toolchain-host-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  toolchainCluster: member-kflux-ocp-p01.7ayg.p1.openshiftapps.com
  enabled: true
  capacityThresholds:
    maxNumberOfSpaces: 1000
    maxMemoryUtilizationPercent: 90
  placementRoles:
  - cluster-role.toolchain.dev.openshift.com/tenant
