apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/johnbieren/release-service/config/default?ref=218155949de419899a4005541038c0739e0861fd
images:
  - name: quay.io/konflux-ci/release-service
    newName: registry.build02.ci.openshift.org/ci-op-k71py5hx/pipeline
    newTag: redhat-appstudio-release-service-image
namespace: release-service
