apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/seanconroy2021/release-service/config/default?ref=937ef87eab5efed74bf274e3fe5494144a5d66c6
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/redhat-user-workloads/rhtap-release-2-tenant/release-service/release-service
    newTag: on-pr-937ef87eab5efed74bf274e3fe5494144a5d66c6
namespace: release-service
