apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/konflux-ci/release-service/config/default?ref=d7c98e97066b88965d1461fd79e80134ba5e5411
  - release_service_config.yaml

images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: d7c98e97066b88965d1461fd79e80134ba5e5411

namespace: release-service

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: sealights-token-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: release-service-controller-manager
    path: manager-memory-patch.yaml
