extends: relaxed

ignore:
  # we don't control the content of helm charts, so don't enforce our standards on them
  - '**/charts/'
  - '**/templates/'

rules:
  indentation: disable
  line-length: disable
