apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/mintmaker/config/default?ref=b7b58210a1610b4ef2622809c8737d40d7c06854
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=b7b58210a1610b4ef2622809c8737d40d7c06854

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: b7b58210a1610b4ef2622809c8737d40d7c06854
  - name: quay.io/konflux-ci/mintmaker-renovate-image
    newName: quay.io/konflux-ci/mintmaker-renovate-image
    newTag: latest

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

configurations:
- kustomizeconfig.yaml

components:
  - ../components/rh-certs
