apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/mintmaker/config/default?ref=35aae405f973e3ae3c52e2a7f27ecc4f46e4c5c3
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=35aae405f973e3ae3c52e2a7f27ecc4f46e4c5c3

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: 35aae405f973e3ae3c52e2a7f27ecc4f46e4c5c3
  - name: quay.io/konflux-ci/mintmaker-renovate-image
    newName: quay.io/konflux-ci/mintmaker-renovate-image
    newTag: latest

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

configurations:
- kustomizeconfig.yaml

components:
  - ../components/rh-certs
