apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/mintmaker/config/default?ref=64d29c5343dd36ada5edcdac5b1b19e1793369e4
  - https://github.com/konflux-ci/mintmaker/config/renovate?ref=64d29c5343dd36ada5edcdac5b1b19e1793369e4

images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: 64d29c5343dd36ada5edcdac5b1b19e1793369e4

namespace: mintmaker

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

components:
  - ../components/rh-certs
