apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  labels:
    noSourceTransform: "true"
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/kyverno
                environment: staging
                clusterDir: ""
          - list:
              elements: []
  template:
    metadata:
      name: kyverno-{{nameNormalized}}
    spec:
      project: default
      sources:
        - chart: kyverno
          repoURL: https://kyverno.github.io/kyverno/
          targetRevision: 3.3.4
          helm:
            values: |
              admissionController:
                replicas: 3
                initContainer:
                  securityContext: null
                container:
                  securityContext: null
              backgroundController:
                replicas: 3
                securityContext: null
              cleanupController:
                replicas: 3
                securityContext: null
              reportsController:
                replicas: 3
                securityContext: null
              policyReportsCleanup:
                securityContext: null
              webhooksCleanup:
                securityContext: null
              test:
                securityContext: null
              crds:
                migration:
                  securityContext: null
      destination:
        namespace: konflux-kyverno
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 50
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
