apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- ../blackbox
- https://github.com/konflux-ci/mintmaker/config/default?ref=07cca69f9e4f7eaaa32abf9dc02196437e88db11
- https://github.com/konflux-ci/mintmaker/config/renovate?ref=07cca69f9e4f7eaaa32abf9dc02196437e88db11

namespace: mintmaker

images:
- name: quay.io/konflux-ci/mintmaker
  newName: quay.io/konflux-ci/mintmaker
  newTag: 07cca69f9e4f7eaaa32abf9dc02196437e88db11
- name: quay.io/konflux-ci/mintmaker-renovate-image
  newName: quay.io/konflux-ci/mintmaker-renovate-image
  newTag: 3ad8d5856e094a881cc162dc8ddb76e834d757b8

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - path: manager-set-resources-patch.yaml
  - path: manager-enable-pprof-patch.yaml

configurations:
- kustomizeconfig.yaml

components:
  - ../../components/rh-certs
