apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/mintmaker/config/default?ref=53b8ab24474a58706e840e728a93614d29ef8cc4
- https://github.com/konflux-ci/mintmaker/config/renovate?ref=53b8ab24474a58706e840e728a93614d29ef8cc4

namespace: mintmaker

images:
- name: quay.io/konflux-ci/mintmaker
  newName: quay.io/konflux-ci/mintmaker
  newTag: 53b8ab24474a58706e840e728a93614d29ef8cc4
- name: quay.io/konflux-ci/mintmaker-renovate-image
  newName: quay.io/konflux-ci/mintmaker-renovate-image
  newTag: 41715ff841094290ce07c7e4ed3a2a37db0c4695

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - path: manager_patch.yaml

configurations:
- kustomizeconfig.yaml
