apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/grafana/base?ref=8d555324d30236ba09d52e70cdcc71d197ade23f

images:
- name: quay.io/redhat-appstudio/o11y
  newName: quay.io/redhat-appstudio/o11y
  newTag: 8d555324d30236ba09d52e70cdcc71d197ade23f

patches:
  - path: auto-assign-role-patch.yaml
    target:
      name: grafana-oauth
      kind: Grafana
