apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/grafana/base?ref=0839c503c6f12f34602bacaaa3c880ab2ba80349

images:
- name: quay.io/redhat-appstudio/o11y
  newName: quay.io/redhat-appstudio/o11y
  newTag: 0839c503c6f12f34602bacaaa3c880ab2ba80349

patches:
  - path: auto-assign-role-patch.yaml
    target:
      name: grafana-oauth
      kind: Grafana
