apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/enterprise-contract/enterprise-contract-controller/config/crd?ref=6f293a96578d185639cf1c92fa5f8e5f37375171
  - ecp.yaml
  - role.yaml
  - rolebinding.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/enterprise-contract/ec-task-bundle:914425bc954fdbe128d1c501e0c735443b0060bf@sha256:b666020fe297dcaffd362b627e80adcde1c625ee1145e5fcf489c9e7a3fa4107
      - verify_ec_task_git_url=https://github.com/enterprise-contract/ec-cli.git
      - verify_ec_task_git_revision=914425bc954fdbe128d1c501e0c735443b0060bf
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
