apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/enterprise-contract/enterprise-contract-controller/config/crd?ref=b8b0d074cabfa34a180b67a3d602400c3a956b2a
  - ecp.yaml
  - role.yaml
  - rolebinding.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/enterprise-contract/ec-task-bundle:3c9ee8ab150b47a0638b9ac2c3e05d2d376c952d@sha256:6299beefc500438e711c0ebbd8b4f4113671799a683449931787781b0b6a3fbe
      - verify_ec_task_git_url=https://github.com/enterprise-contract/ec-cli.git
      - verify_ec_task_git_revision=3c9ee8ab150b47a0638b9ac2c3e05d2d376c952d
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
