apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/enterprise-contract/enterprise-contract-controller/config/crd?ref=9bacde26dcd1893dc3482752c96d8b882b3f2d7e
  - ecp.yaml
  - role.yaml
  - rolebinding.yaml
  - download-service.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/enterprise-contract/ec-task-bundle:0527fad71b065e9a0694a30ca70dbf04625ac811@sha256:2ff64769abbd4826d782d3e9dc0826a59e7971f317048f0080c89d9776fd6a45
      - verify_ec_task_git_url=https://github.com/enterprise-contract/ec-cli.git
      - verify_ec_task_git_revision=0527fad71b065e9a0694a30ca70dbf04625ac811
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
