apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/argocd-roles
  - ../base/external-secrets
  - ../base/rbac
  - https://github.com/redhat-appstudio/application-service/config/default?ref=f50e3eecf84043f0db1f578e0fb93975311f3763
  - https://github.com/redhat-appstudio/application-service/config/prometheus/?ref=f50e3eecf84043f0db1f578e0fb93975311f3763

components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling

images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/redhat-appstudio/application-service
    newTag: f50e3eecf84043f0db1f578e0fb93975311f3763

configMapGenerator:
  - literals:
    - GITHUB_ORG="redhat-appstudio-appdata"
    name: github-config
    behavior: replace
  - literals:
    - ENVIRONMENT="production"
    name: feature-flag-config
    behavior: replace

patches:
  - path: has-github-token-patch.yaml
    target:
      name: has-github-token
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
namespace: application-service
