kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-resolutionrequests
rules:
  - apiGroups:
    - "resolution.tekton.dev"
    resources:
      - "resolutionrequests"
    verbs:
      - "create"
      - "get"
      - "list"
      - "watch"
      - "delete"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-resolutionrequests
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: konflux-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-resolutionrequests
