apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:edbef45bf081f059f564bcfe76b886d166e93638
      additional-params:
      - build-platforms
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build:edbef45bf081f059f564bcfe76b886d166e93638
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta:edbef45bf081f059f564bcfe76b886d166e93638
    - name: docker-build-multi-platform-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta:edbef45bf081f059f564bcfe76b886d166e93638
      additional-params:
      - build-platforms
    - name: maven-zip-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build:edbef45bf081f059f564bcfe76b886d166e93638
    - name: maven-zip-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build-oci-ta:edbef45bf081f059f564bcfe76b886d166e93638
