apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:20d2e31c88b95be49b40c295b21acedd150ad741
      additional-params:
      - build-platforms
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build:20d2e31c88b95be49b40c295b21acedd150ad741
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta:20d2e31c88b95be49b40c295b21acedd150ad741
    - name: docker-build-multi-platform-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta:20d2e31c88b95be49b40c295b21acedd150ad741
      additional-params:
      - build-platforms
    - name: maven-zip-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build:20d2e31c88b95be49b40c295b21acedd150ad741
    - name: maven-zip-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build-oci-ta:20d2e31c88b95be49b40c295b21acedd150ad741
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder:20d2e31c88b95be49b40c295b21acedd150ad741
