apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - dashboards
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/grafana/base?ref=8e80e6fee18998cc4839ce10b21ee0ce357fc443

images:
- name: quay.io/redhat-appstudio/o11y
  newName: quay.io/redhat-appstudio/o11y
  newTag: 8e80e6fee18998cc4839ce10b21ee0ce357fc443

patches:
  - path: grafana-resources-patch.yaml
    target:
      name: grafana-oauth
      kind: Grafana
  - path: auto-assign-role-patch.yaml
    target:
      name: grafana-oauth
      kind: Grafana
