apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
  - tenants-rbac/konflux-perfscale-1-tenant
  - tenants-rbac/konflux-perfscale-2-tenant
  - tenants-rbac/konflux-perfscale-3-tenant
