apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multi-platform-controller
resources:
- base-snapshot
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=0e74cc338a3d1839acddb148c5349dbed47a453d
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=0e74cc338a3d1839acddb148c5349dbed47a453d
- host-config-cm.yaml
images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: 0e74cc338a3d1839acddb148c5349dbed47a453d
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: 0e74cc338a3d1839acddb148c5349dbed47a453d
patches:
- path: patches/logs-in-console-format-cmd-arg-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: multi-platform-controller
