apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=602d12ee46b83380c52e95dad6949451c12db19b
- ../base/external-secrets

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: 602d12ee46b83380c52e95dad6949451c12db19b

namespace: notification-controller

patches:
  - path: external-secret-path.yaml
    target:
      name: aws-sns-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1      
  - path: topic_region_add.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
