apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=0ef85c1c7674ab960df4fcb0020dd4e416a5d7ab
- ../base/external-secrets

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: 0ef85c1c7674ab960df4fcb0020dd4e416a5d7ab

namespace: notification-controller

patches:
  - path: external-secret-path.yaml
    target:
      name: aws-sns-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1
  - path: topic_region_add.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
  - path: pipelinerun_filters.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
