apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=625a5ebb6e8fbc031e0b97e2a07f36add922bb76
- ../base/external-secrets

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: 625a5ebb6e8fbc031e0b97e2a07f36add922bb76

namespace: notification-controller

patches:
  - path: external-secret-path.yaml
    target:
      name: aws-sns-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1      
  - path: topic_region_add.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
