apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base-snapshot
- https://github.com/konflux-ci/project-controller/config/default?ref=a159d75c425ee867e3234a8afcfe053356cfb554
images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: a159d75c425ee867e3234a8afcfe053356cfb554
namespace: project-controller
