resources:
  - allow-argocd-to-manage.yaml
  - https://github.com/redhat-appstudio/jvm-build-service/deploy/crds/base?ref=bcbb4d8359e8ce97188e97024bf29cfdb1d84c2e
  - https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/base?ref=bcbb4d8359e8ce97188e97024bf29cfdb1d84c2e
  - https://github.com/redhat-appstudio/jvm-build-service/deploy/operator/config?ref=bcbb4d8359e8ce97188e97024bf29cfdb1d84c2e
  - monitoring.yaml
# Skip applying the jvm-build-service operands (SystemConfig) while the jvm-build-service operator is being installed.
# See more information about this option, here:
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
namespace: jvm-build-service
images:
  - name: hacbs-jvm-operator
    newName: registry.build04.ci.openshift.org/ci-op-3gs13jfb/pipeline
    newTag: redhat-appstudio-jvm-build-service-image
patches:
  - path: ./operator_env_patch.yaml
    target:
      kind: Deployment
      name: hacbs-jvm-operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
