apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/project-controller/config/default?ref=7b0a5bc438678da5febcac0baa3aef9cf59a6cb6

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 7b0a5bc438678da5febcac0baa3aef9cf59a6cb6

namespace: project-controller
