apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/project-controller/config/default?ref=a8b27046be6a93b4a24fb60346ffb39b659bfb8e

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: a8b27046be6a93b4a24fb60346ffb39b659bfb8e

namespace: project-controller
