apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/project-controller/config/default?ref=e0e7bfe9a57a30c53007c8eb86b4861939ed10fd

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: e0e7bfe9a57a30c53007c8eb86b4861939ed10fd

namespace: project-controller
