---
- op: add
  path: /spec/platforms/openshift/pipelinesAsCode/settings
  value:
    application-name: Konflux OCP
    custom-console-name: Konflux OCP
    custom-console-url: https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com
    custom-console-url-pr-details: https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/ns/{{ namespace }}/pipelinerun/{{ pr }}
    custom-console-url-pr-tasklog: https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/ns/{{ namespace }}/pipelinerun/{{ pr }}/logs/{{ task }}
