apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/integration-service/config/default?ref=878dbdf03989fed4da0024f47a5ce498e23a9b32
- https://github.com/konflux-ci/integration-service/config/snapshotgc?ref=878dbdf03989fed4da0024f47a5ce498e23a9b32

images:
- name: quay.io/konflux-ci/integration-service
  newName: quay.io/konflux-ci/integration-service
  newTag: 878dbdf03989fed4da0024f47a5ce498e23a9b32

configMapGenerator:
- name: integration-config
  literals:
    - CONSOLE_NAME="Konflux Dev version"
    - CONSOLE_URL=""
    - CONSOLE_URL_TASKLOG=""
    - INTEGRATION_NS="integration-service"
    - PAC_SECRET="pipelines-as-code-secret"
    - GITHUBAPPLICATION_ID="github-application-id"
    - GITHUBPRIVATE_KEY="github-private-key"
- name: pipelinerun-options
  literals:
    - PIPELINE_TIMEOUT="6h"
    - TASKS_TIMEOUT="4h"
    - FINALLY_TIMEOUT="2h"

namespace: integration-service

patches:
  - path: manager_resources_patch.yaml
  - path: snapshotgc_inputs_patch.yaml
    target:
      kind: CronJob
      name: snapshot-garbage-collector
components:
  - ../rh-certs
