apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/integration-service/config/default?ref=bb2ece98adcba6f04c796b43111b3f1fe9c8609e
- https://github.com/konflux-ci/integration-service/config/snapshotgc?ref=bb2ece98adcba6f04c796b43111b3f1fe9c8609e

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/redhat-appstudio/integration-service
  newTag: bb2ece98adcba6f04c796b43111b3f1fe9c8609e

configMapGenerator:
- name: integration-config
  literals:
    - CONSOLE_NAME="Konflux Dev version"
    - CONSOLE_URL=""
    - CONSOLE_URL_TASKLOG=""
- name: pipelinerun-options
  literals:
    - PIPELINE_TIMEOUT="3h"
    - TASKS_TIMEOUT="2h"
    - FINALLY_TIMEOUT="1h"

namespace: integration-service

patches:
  - path: manager_resources_patch.yaml
  - path: snapshotgc_inputs_patch.yaml
    target:
      kind: CronJob
      name: snapshot-garbage-collector

components:
  - ../rh-certs
