apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/integration-service/config/default?ref=e65928125c063bbc8fec211a78b875bfdbc7932d
  - https://github.com/konflux-ci/integration-service/config/snapshotgc?ref=e65928125c063bbc8fec211a78b875bfdbc7932d
images:
  - name: quay.io/konflux-ci/integration-service
    newName: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service
    newTag: on-pr-e65928125c063bbc8fec211a78b875bfdbc7932d
configMapGenerator:
  - name: integration-config
    literals:
      - CONSOLE_NAME="Konflux Dev version"
      - CONSOLE_URL=""
      - CONSOLE_URL_TASKLOG=""
  - name: pipelinerun-options
    literals:
      - PIPELINE_TIMEOUT="6h"
      - TASKS_TIMEOUT="4h"
      - FINALLY_TIMEOUT="2h"
namespace: integration-service
patches:
  - path: manager_resources_patch.yaml
  - path: snapshotgc_inputs_patch.yaml
    target:
      kind: CronJob
      name: snapshot-garbage-collector
components:
  - ../rh-certs
