apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  prometheus:
    enabled: true
    service:
      port: 8080
  resources:
   requests:
     cpu: 100m
     memory: 512Mi
   limits:
     memory: 512Mi
  certController:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
  webhook:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
---

apiVersion: v1
kind: Service
metadata:
  name: cluster-external-secrets-metrics
  namespace: external-secrets-operator
  annotations:
    ignore-check.kube-linter.io/dangling-service: "False positive"
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: cluster
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: cluster
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
spec:
  endpoints:
  - port: metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/instance: cluster
