apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/integration-service/config/default?ref=f4cc2b70958230939a719a3e298e9c6837c75c96
- https://github.com/konflux-ci/integration-service/config/snapshotgc?ref=f4cc2b70958230939a719a3e298e9c6837c75c96

images:
- name: quay.io/redhat-appstudio/integration-service
  newName: quay.io/redhat-appstudio/integration-service
  newTag: f4cc2b70958230939a719a3e298e9c6837c75c96

configMapGenerator:
- name: integration-config
  literals:
    - CONSOLE_NAME="Konflux Staging"
    - CONSOLE_URL="https://console.dev.redhat.com/preview/application-pipeline/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}"
    - CONSOLE_URL_TASKLOG="https://console.dev.redhat.com/preview/application-pipeline/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}/logs/{{ .TaskName }}"
- name: pipelinerun-options
  literals:
    - PIPELINE_TIMEOUT="3h"
    - TASKS_TIMEOUT="2h"
    - FINALLY_TIMEOUT="1h"

namespace: integration-service

patches:
  - path: manager_resources_patch.yaml
