apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/integration-service/config/default?ref=08eb8bcb1ca3b7d3822dcedcdbb2a1d83a5ed503
- https://github.com/konflux-ci/integration-service/config/snapshotgc?ref=08eb8bcb1ca3b7d3822dcedcdbb2a1d83a5ed503

images:
- name: quay.io/konflux-ci/integration-service
  newName: quay.io/konflux-ci/integration-service
  newTag: 08eb8bcb1ca3b7d3822dcedcdbb2a1d83a5ed503

configMapGenerator:
- name: integration-config
  literals:
    - CONSOLE_NAME="Konflux Staging"
    - CONSOLE_URL="https://konflux-ui.apps.stone-stg-rh01.l2vh.p1.openshiftapps.com/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}"
    - CONSOLE_URL_TASKLOG="https://konflux-ui.apps.stone-stg-rh01.l2vh.p1.openshiftapps.com/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}/logs/{{ .TaskName }}"
    - INTEGRATION_NS="integration-service"
    - PAC_SECRET="pipelines-as-code-secret"
    - GITHUBAPPLICATION_ID="github-application-id"
    - GITHUBPRIVATE_KEY="github-private-key"
- name: pipelinerun-options
  literals:
    - PIPELINE_TIMEOUT="6h"
    - TASKS_TIMEOUT="4h"
    - FINALLY_TIMEOUT="2h"

namespace: integration-service

patches:
  - path: manager_resources_patch.yaml
