apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - https://github.com/redhat-appstudio/remote-secret/config/overlays/openshift_vault?ref=10879277956566a9dc65ce822ca7ac9d5989590a

namespace: remotesecret

images:
  - name:  quay.io/redhat-appstudio/remote-secret-controller
    newName: quay.io/redhat-appstudio/remote-secret-controller
    newTag: 10879277956566a9dc65ce822ca7ac9d5989590a

patches:
  - target:
      kind: ConfigMap
      name: remote-secret-controller-manager-environment-config
    path: config-patch.json
