apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/build-service/config/default?ref=da65d94933f0cfb2f1a4b747cde7e9094a62b2d9

namespace: build-service

images:
- name: quay.io/konflux-ci/build-service
  newName: quay.io/konflux-ci/build-service
  newTag: da65d94933f0cfb2f1a4b747cde7e9094a62b2d9

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

components:
  - ../../components/rh-certs

patches:
  - path: manager_resources_patch.yaml
