apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/build-service/config/default?ref=3cce59b269609293906cc5d0e82fef5ccf095b38

namespace: build-service

images:
- name: quay.io/konflux-ci/build-service
  newName: quay.io/konflux-ci/build-service
  newTag: 3cce59b269609293906cc5d0e82fef5ccf095b38

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
