apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-rbac-proxy
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/image-rbac-proxy/deploy/base?ref=1d93006c97025ca03f0d709e86fe5235b69c05f5

images:
- name: quay.io/konflux-ci/image-rbac-proxy
  newName: quay.io/konflux-ci/image-rbac-proxy
  newTag: 1d93006c97025ca03f0d709e86fe5235b69c05f5
