apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configure-service-account.yaml
- configure-logforwarder.yaml

namespace: "openshift-logging"

generatorOptions:
  disableNameSuffixHash: true