apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
configMapGenerator:
  - name: config
    literals:
      - config=*
generatorOptions:
  labels:
    app.kubernetes.io/name: repository-validator
namespace: repository-validator
