apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- https://github.com/konflux-ci/build-service/config/default?ref=a1942c2be04df79264e7a1ab6d96c0f57a52b51b

namespace: build-service

images:
- name: quay.io/konflux-ci/build-service
  newName: quay.io/konflux-ci/build-service
  newTag: a1942c2be04df79264e7a1ab6d96c0f57a52b51b

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: image-expiration-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: pac-webhook-insecure-ssl-patch.yaml

components:
  - ../components/rh-certs
