apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/rcerven/build-service/config/default?ref=941a506d992723cf447a0c31729f45b41c74bdb2
namespace: build-service
images:
  - name: quay.io/konflux-ci/build-service
    newName: registry.build03.ci.openshift.org/ci-op-gt2zqb87/pipeline
    newTag: redhat-appstudio-build-service-image
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: image-expiration-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: pac-webhook-insecure-ssl-patch.yaml
components:
  - ../components/rh-certs
