- name: Ensure the {{ github_application }} github application already exists
  tags: [github]
  uri:
    #url: "https://api.github.com/apps/{{ github_application }}"
    url: "https://github.com/apps/{{ github_application }}"
    method: GET
    return_content: no
    headers:
      Accept: "application/vnd.github.v3+json"
  register: github_app
