kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: monitoring-workload-konflux-o11y-exporters
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  appstudio.redhat.com/member-cluster: "true"
              values:
                environment: staging
          - list:
              elements:
                - exporter: kaexporter
                  sourceRoot: components/monitoring/exporters/kaexporter
  template:
    metadata:
      name: konflux-o11y-exporters-{{exporter}}-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{sourceRoot}}/{{values.environment}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: konflux-o11y-exporters
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
