apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- validate-namespace-labels/validate-namespace-labels.yaml
- propagate-namespace-labels/propagate-namespace-labels.yaml
- kyverno-rbac.yaml
