apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- validate_namespace_labels/validate_namespace_labels.yaml
- propagate_namespace_labels/propagate_namespace_labels.yaml
- kyverno-rbac.yaml
