---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubearchive/kubearchive/releases/download/v0.1.0/kubearchive.yaml
- rbac.yaml
- database-secret.yaml
namespace: kubearchive
