apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-kubearchive-logging
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"

resources:
- rbac.yaml
- sa.yaml
- scc.yaml
<<<<<<< HEAD
=======

>>>>>>> fe12a26bc (KAR-589: setup stone-prod-p02 config for kubearchive-logging)
