apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-kubearchive-logging
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"

resources:
- vector-pre.yaml
- rbac.yaml
