---
apiVersion: v1
kind: Namespace
metadata:
  name: product-kubearchive-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  # Create namespace first
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: kubearchive-logging-scc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
defaultAllowPrivilegeEscalation: false
forbiddenSysctls:
- '*'
fsGroup:
  type: RunAsAny
groups: []
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- runtime/default
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:product-kubearchive-logging:vector-kubearchive-log-collector
- system:serviceaccount:product-kubearchive-logging:loki
- system:serviceaccount:product-kubearchive-logging:loki-sa
- system:serviceaccount:product-kubearchive-logging:vector-kubearchive-log-collector-grafana
- system:serviceaccount:product-kubearchive-logging:vector-kubearchive-log-collector-loki
- system:serviceaccount:product-kubearchive-logging:vector-kubearchive-log-collector-loki-canary
volumes:
- configMap
- emptyDir
- hostPath
- projected
- secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearchive-vector-scc-user
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Before workloads
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - kubearchive-logging-scc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-scc-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Before workloads
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubearchive-vector-scc-user
subjects:
- kind: ServiceAccount
  name: vector-kubearchive-log-collector
  namespace: product-kubearchive-logging
- kind: ServiceAccount
  name: loki
  namespace: product-kubearchive-logging
- kind: ServiceAccount
  name: loki-sa
  namespace: product-kubearchive-logging
- kind: ServiceAccount
  name: vector-kubearchive-log-collector-grafana
  namespace: product-kubearchive-logging
- kind: ServiceAccount
  name: vector-kubearchive-log-collector-loki
  namespace: product-kubearchive-logging
- kind: ServiceAccount
  name: vector-kubearchive-log-collector-loki-canary
  namespace: product-kubearchive-logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-sa
  namespace: product-kubearchive-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Before workloads
    # This annotation links the SA to the AWS IAM Role
    eks.amazonaws.com/role-arn: "arn:aws:iam::663944276957:role/stone-stg-rh01-loki-storage-role"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-kubearchive-log-collector-loki
  namespace: product-kubearchive-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Before workloads
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-kubearchive-log-collector-grafana
  namespace: product-kubearchive-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Before workloads
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-kubearchive-log-collector-loki-canary
  namespace: product-kubearchive-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Before workloads
