apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ring-deployments
namespace: openshift-gitops
nameSuffix: -ring-0

## No patches until those applications are onboarded to the new standards
