apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mintmaker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: mintmaker-controller-manager
      securityContext:
        fsGroup: 1001120000
      initContainers:
      - name: volume-permissions
        image: registry.access.redhat.com/ubi9:9.5
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "256Mi"
            cpu: "0.5"
        command: ["sh", "-c", "chown -R 1001120000:1001120000 /var/lib/redis/data && chmod -R 750 /var/lib/redis/data"]
        volumeMounts:
        - name: redis-data
          mountPath: /var/lib/redis/data
      containers:
        - name: redis
          image: registry.redhat.io/rhel9/redis-7:9.5
          ports:
            - containerPort: 6379
          command: ["container-entrypoint"]
          args: ["run-redis"]
          resources:
            requests:
              memory: "800Mi"
              cpu: "0.75"
            limits:
              memory: "1Gi"
              cpu: "1"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001120000
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: redis-data
              mountPath: /var/lib/redis/data
            - name: redis-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: redis-config
          configMap:
            name: redis-config
