resources:
- internal_service_request_role.yaml
- internal_service_request_role_binding.yaml
- internal_service_request_service_account.yaml
- internal_service_service_account_token.yaml
- internal-services.yaml
- https://github.com/konflux-ci/internal-services/config/crd?ref=c189f03a834b65830676d2dbe16104db6a5e4677

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal-services
