resources:
- internal_service_request_role.yaml
- internal_service_request_role_binding.yaml
- internal_service_request_service_account.yaml
- internal_service_service_account_token.yaml
- internal-services.yaml
- https://github.com/konflux-ci/internal-services/config/crd?ref=680fa7275ac857456533e7e9791df679193cd89a

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal-services
