resources:
- internal_service_request_role.yaml
- internal_service_request_role_binding.yaml
- internal_service_request_service_account.yaml
- internal_service_service_account_token.yaml
- internal-services.yaml
- https://github.com/konflux-ci/internal-services/config/crd?ref=79dc9f9d04d2926cd3d7ac64c512b332cd29692f

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: internal-services
