apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- loki-secret.yaml

generators:
- vector-helm-generator.yaml
- loki-helm-generator.yaml
- grafana-helm-generator.yaml
