apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  ignore-check.kube-linter.io/drop-net-raw-capability: |
    "Vector runs requires access to socket."
  ignore-check.kube-linter.io/run-as-non-root: |
    "Vector runs as Root and attach host Path."
  ignore-check.kube-linter.io/sensitive-host-mounts: |
    "Vector runs requires certain host mounts to watch files being created by pods."

resources:
- ../base
- loki-secret.yaml

generators:
- vector-helm-generator.yaml
- loki-helm-generator.yaml
- grafana-helm-generator.yaml
