---
# Ultra-simplified Loki configuration for development
deploymentMode: SingleBinary

# Disable gateway - not needed for SingleBinary
gateway:
  enabled: false

# Service Account configuration to match SCC  
serviceAccount:
  create: false
  name: vector-kubearchive-log-collector-loki

# Disable canary
lokiCanary:
  enabled: false

# Single binary configuration with proper volume mounts
singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: false  # Use ephemeral storage for dev
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
    unhealthyPodEvictionPolicy: AlwaysAllow
  # Add writable volume mounts for Loki data directories
  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki

  extraVolumes:
    - name: loki-storage
      emptyDir: {}


# Basic Loki configuration
loki:
  commonConfig:
    replication_factor: 1
    path_prefix: /var/loki  # This directory will be writable via volume mount
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  # Configure ingestion limits to handle Vector's data volume
  limits_config:
    ingestion_rate_mb: 16          # Increase from default 4MB to 16MB per second
    ingestion_burst_size_mb: 32    # Allow bursts up to 32MB
    max_line_size: 256KB           # Allow larger log lines
    max_streams_per_user: 10000    # Allow more streams per tenant
    max_global_streams_per_user: 50000
    reject_old_samples: false      # Don't reject old samples
    reject_old_samples_max_age: 168h  # Accept samples up to 7 days old
  # Required storage configuration for Helm chart
  storage:
    type: filesystem
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  storage_config:
    filesystem:
      directory: /var/loki/chunks
  # Configure ruler storage to use the writable volume
  ruler:
    storage:
      type: local
      local:
        directory: /var/loki/ruler
  # Configure compactor to use writable volume
  compactor:
    working_directory: /var/loki/compactor

# Security contexts for OpenShift
podSecurityContext:
  runAsNonRoot: false
  allowPrivilegeEscalation: false

containerSecurityContext:
  runAsNonRoot: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true  # Keep read-only root filesystem for security

# Disable test pods
test:
  enabled: false

# Disable sidecar completely to avoid loki-sc-rules container
sidecar:
  rules:
    enabled: false
  datasources:
    enabled: false

# Disable ALL memcached components to avoid exporter containers and PDB issues
chunksCache:
  enabled: false
  replicas: 0

resultsCache:
  enabled: false
  replicas: 0

memcached:
  enabled: false

memcachedResults:
  enabled: false

memcachedChunks:
  enabled: false

memcachedFrontend:
  enabled: false

memcachedIndexQueries:
  enabled: false

memcachedIndexWrites:
  enabled: false

# Explicitly disable all other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
ruler:
  replicas: 0
