apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: loki
name: loki
repo: https://grafana.github.io/helm-charts
version: 6.30.1
releaseName: vector-kubearchive-log-collector
namespace: product-kubearchive-logging
valuesFile: loki-helm-values.yaml
