---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubearchive-loki
  namespace: product-kubearchive-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        key: staging/kubearchive/loki
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: kubearchive-loki
    template:
      data:
        USERNAME: '{{ .username }}'
        PASSWORD: '{{ .password }}'
