apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-claim-configmap
  namespace: crossplane-system
data:
  namespace-claim-cleaner.sh: |
    #!/bin/bash
    set -eo pipefail
    CURRENT_TIME=$(date +%s)
    namespaces=$(kubectl get namespaces.eaas.konflux-ci.dev -o json | jq -c '.items[] | "\(.metadata.name) \(.metadata.creationTimestamp)"')
    while read -r namespace creationTime; do
      export NAME="$namespace"
      export CREATION_TIME=$(date -d "$creationTime" +%s)
      AGE=$((CURRENT_TIME - CREATION_TIME))
      if [ $AGE -gt 14400 ]; then
        kubectl delete namespaces.eaas.konflux-ci.dev $NAME
      fi
    done <<< "$namespaces"
