apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-claim-configmap
  namespace: crossplane-control-plane
data:
  namespace-claim-cleaner.sh: |
    #!/bin/bash

    CURRENT_TIME=$(date +%s)
    kubectl get namespaces.eaas.konflux-ci.dev -o json | jq -c '.items[]' | while read -r claim; do
      CREATION_TIMESTAMP=$(echo $claim | jq -r '.metadata.creationTimestamp')
      CREATION_TIME=$(date -d "$CREATION_TIMESTAMP" +%s)
      AGE=$((CURRENT_TIME - CREATION_TIME))
      if [ $AGE -gt (2*24*3600) ]; then
        NAME=$(echo $claim | jq -r '.metadata.name')
        echo "Deleting NamespaceClaim: $NAME"
        kubectl delete namespaces.eaas.konflux-ci.dev $NAME
      fi
    done
