resources:
  - ../base
  - rbac
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/registry/base?ref=21c4f16228d2294435bc236ade2b91f61e887171

images:
  - name: quay.io/redhat-appstudio/o11y
    newName: quay.io/redhat-appstudio/o11y
    newTag: 21c4f16228d2294435bc236ade2b91f61e887171
