resources:
  - ../base
  - rbac
  - https://github.com/redhat-appstudio/o11y/config/exporters/monitoring/registry/base?ref=400329e6dbc1698184bc479119218eac364b2cc9

images:
  - name: quay.io/redhat-appstudio/o11y
    newName: quay.io/redhat-appstudio/o11y
    newTag: 400329e6dbc1698184bc479119218eac364b2cc9

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: registry-exporter-ds
        namespace: appstudio-registry-exporter
      spec:
        template:
          spec:
            containers:
              - name: exporters
                env:
                - name: QUAY_URL
                  value: quay.io/redhat-user-workloads-stage/appstudio-registry-exporter/appstudio-registry-exporter
