apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: konflux-kyverno

generators:
- kyverno-helm-generator.yaml

images:
  - name: reg.kyverno.io/kyverno/kyverno
    newName: quay.io/konflux-ci/kyverno/kyverno
    newTag: b97c56a0d4184211b4ac298ed92b39531f25c9fa
  - name: reg.kyverno.io/kyverno/kyvernopre
    newName: quay.io/konflux-ci/kyverno/kyverno-init
    newTag: b97c56a0d4184211b4ac298ed92b39531f25c9fa
  - name: reg.kyverno.io/kyverno/background-controller
    newName: quay.io/konflux-ci/kyverno/kyverno-background
    newTag: b97c56a0d4184211b4ac298ed92b39531f25c9fa
  - name: reg.kyverno.io/kyverno/cleanup-controller
    newName: quay.io/konflux-ci/kyverno/kyverno-cleanup
    newTag: b97c56a0d4184211b4ac298ed92b39531f25c9fa
  - name: reg.kyverno.io/kyverno/kyverno-cli
    newName: quay.io/konflux-ci/kyverno/kyverno-cli
    newTag: b97c56a0d4184211b4ac298ed92b39531f25c9fa

# set resources to jobs
patches:
- path: job_resources.yaml
  target:
    group: batch
    kind: Job
    name: konflux-kyverno-migrate-resources
    version: v1
