apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- common
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=93cdddc40710394c5012d589d10096c346b13f8c
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=93cdddc40710394c5012d589d10096c346b13f8c


images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: 93cdddc40710394c5012d589d10096c346b13f8c
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: 93cdddc40710394c5012d589d10096c346b13f8c
