apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- common
- rbac
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=3dbbae7c8682ff68fbfa9188c3ec044f29258332
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=3dbbae7c8682ff68fbfa9188c3ec044f29258332

images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: 3dbbae7c8682ff68fbfa9188c3ec044f29258332
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: 3dbbae7c8682ff68fbfa9188c3ec044f29258332
