apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- common
- rbac
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=922ac8eb55ede4f797ac75fe97708d778f6f1f1a
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=922ac8eb55ede4f797ac75fe97708d778f6f1f1a

images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: 922ac8eb55ede4f797ac75fe97708d778f6f1f1a
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: 922ac8eb55ede4f797ac75fe97708d778f6f1f1a
