---
# This ansible playbook will locally write out configuration overlays for a new cluster based on templates.

# TODO -
#   * Create github app
#   * Vault: Populate github app token into {{ env }}/pipeline-service/{{ shortname }}/github-app
#
#   APIs:
#     https://api.github.com/apps/red-hat-konflux
#     https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-a-github-app-from-a-manifest
#     NOTE - you can only retrieve the client secret, webhook secret, and rsa private key if you are creating the app via the API.
#            the most basic flow is: confirm that it exists and stop the user if it doesnt
#             * confirm it exists in github and move on
#             * confirm it exists in vault and move on
#             If it doesn't exist in either github or vault, then create it in github and populate vault.
#
#   * Other pipeline service secrets:
#     * {{ env }}/pipeline-service/{{ shortname }}/chains-signing-secret
#
- name: Create and patch YAML files
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: cutename
      prompt: "Cute name of the cluster (like rh09)"
      private: false
    - name: shortname
      prompt: "Short name of the cluster (like kflux-prd-rh09)"
      private: false
    - name: longname
      prompt: "Long name of the cluster (like kflux-prd-rh09.1bz7)"
      private: false
    - name: env
      prompt: "What environment (one of {{allowed_envs}})"
      private: false
    - name: network
      prompt: "What network (one of {{allowed_networks}})"
      private: false

  vars:
    vault_addr: "https://vault.devshift.net"

    dst: "{{ lookup('env', 'PWD') }}"
    github_application: "red-hat-konflux-{{ shortname }}"
    required_vars:
      - shortname
      - longname
      - env
    controlplane_cluster: appsrep09ue1
    allowed_envs:
      - production
      - staging
    allowed_networks:
      - public
      - private
    templated_components:
      - backup
      - build-service
      - integration
      - konflux-info
      - konflux-rbac
      - konflux-ui
      - kyverno
      - mintmaker
      - monitoring/logging
      - monitoring/prometheus
      - multi-platform-controller
      - namespace-lister
      - pipeline-service

    argo_cd_app_files:
      - "{{ dst }}/argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml"
      - "{{ dst }}/argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/build-service/build-service.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/integration/integration.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/konflux-info/konflux-info.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/konflux-rbac/konflux-rbac.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/mintmaker/mintmaker.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/multi-platform-controller/multi-platform-controller.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml"
      - "{{ dst }}/argo-cd-apps/base/member/infra-deployments/pipeline-service/pipeline-service.yaml"

    expected_vault_secrets:
      - 'stonesoup/{{ env }}/pipeline-service/{{ shortname }}/github-app'
      - 'stonesoup/{{ env }}/pipeline-service/{{ shortname }}/chains-signing-secret'
      - 'stonesoup/{{ env }}/platform/terraform/generated/{{ shortname }}/backup-bucket'
      - 'stonesoup/{{ env }}/platform/terraform/generated/{{ shortname }}/plnsvc-database'
      - 'stonesoup/{{ env }}/platform/terraform/generated/{{ shortname }}/tekton-bucket'
      - 'stonesoup/{{ env }}/platform/terraform/generated/{{ shortname }}/aws-ssh-key'
      - 'stonesoup/{{ env }}/platform/terraform/generated/{{ shortname }}/aws-account'
      - 'stonesoup/{{ env }}/platform/terraform/generated/{{ shortname }}/ibm-api-key'

      #- 'stonesoup/{{ env }}/platform/terraform/generated/{{ shortname }}/ibm-s390x-ssh-key'
      #- 'stonesoup/{{ env }}/platform/terraform/generated/{{ shortname }}/ibm-ppc64le-ssh-key'

    github_commit_vars:
      - slug: openshift-pipelines/tektoncd-results-for-konflux
        varname: commit_id_tektoncd_results_for_konflux
      - slug: openshift-pipelines/pipeline-service-exporter
        varname: commit_id_pipeline_service_exporter
      - slug: konflux-ci/build-definitions
        varname: commit_id_build_definitions
      - slug: konflux-ci/multi-platform-controller
        varname: commit_id_multi_platform_controller

  pre_tasks:
    - name: Ensure required variables are defined
      tags: [always]
      fail:
        msg: "Required variable {{ item }} has not been provided"
      when: "vars[item] is undefined or vars[item] == ''"
      loop: "{{ required_vars }}"
    - name: Make sure env is sane
      tags: [always]
      fail:
        msg: "Variable env must be one of {{allowed_envs}}, not {{env}}"
      when: "vars['env'] not in vars['allowed_envs']"
    - name: Make sure network is sane
      tags: [always]
      fail:
        msg: "Variable network must be one of {{allowed_networks}}, not {{network}}"
      when: "vars['network'] not in vars['allowed_networks']"
    - name: Setup cute variants of the environment name (for prod)
      tags: [always]
      set_fact:
        cuteenv: prod
        cutestenv: prd
      when: "vars['env'] == 'production'"
    - name: Setup cute variants of the environment name (for staging)
      tags: [always]
      set_fact:
        cuteenv: stage
        cutestenv: stg
      when: "vars['env'] == 'staging'"
    - name: Determine the latest github commits
      tags: [always]
      include_tasks: tasks/github/find-latest-commits.yaml
      loop: "{{ github_commit_vars }}"
      vars:
        slug: "{{ item.slug }}"
        varname: "{{ item.varname }}"
    - name: Determine quay.io digest
      tags: [always]
      include_tasks: tasks/quay/find-digest.yaml
      vars:
        registry: quay.io
        repo: konflux-ci/appstudio-utils
        tag: "{{ commit_id_build_definitions }}"
        varname: quay_digest_build_definitions

  tasks:
    - name: Login to vault
      tags: [vault]
      include_tasks: tasks/vault/login.yaml

    - name: Verify vault secrets exist as expected
      tags: [vault]
      include_tasks: tasks/vault/verify.yaml
      loop: "{{ expected_vault_secrets }}"
      loop_control:
        loop_var: path

    - name: Patch ApplicationSet files to include new cluster reference
      tags: [applicationsets]
      include_tasks: tasks/applicationsets.yaml
      loop: "{{ argo_cd_app_files }}"
      loop_control:
        loop_var: filename

    - name: Copy cluster-specific component manifests
      tags: [components]
      include_tasks: tasks/components.yaml
      loop: "{{ templated_components }}"
      loop_control:
        loop_var: component
