apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/image-controller/config/default?ref=e138500d2d42e4fd2027b44c0ee4f66e2d036b98

images:
- name: quay.io/konflux-ci/image-controller
  newName: quay.io/konflux-ci/image-controller
  newTag: e138500d2d42e4fd2027b44c0ee4f66e2d036b98

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml
