apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/image-controller/config/default?ref=e1279b5a9d0efbcd490f15c10a5b1cb3172cbefc

images:
- name: quay.io/konflux-ci/image-controller
  newName: quay.io/konflux-ci/image-controller
  newTag: e1279b5a9d0efbcd490f15c10a5b1cb3172cbefc

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml
  - path: ./pruner_cronjob_resources_patch.yaml
