apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/image-controller/config/default?ref=9987b0820b7b7ae49797ca76d44cd6fc501c13e2

images:
- name: quay.io/konflux-ci/image-controller
  newName: quay.io/konflux-ci/image-controller
  newTag: 9987b0820b7b7ae49797ca76d44cd6fc501c13e2

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml
  - path: ./pruner_cronjob_resources_patch.yaml
  - path: ./notification_resetter_cronjob_resources_patch.yaml
