---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: propagate-cost-center-from-namespace
spec:
  rules:
    - name: propagate-cost-center-from-namespace
      match:
        any:
          - resources:
              kinds:
              - Pod
              namespaceSelector:
                matchLabels:
                  konflux-ci.dev/type: tenant
      preconditions: # ensures that the cost-center label exists in the Namespace
        all:
          - key: "{{ lookup('v1', 'Namespace', request.namespace).metadata.labels.cost-center }}"
            operator: NotEquals
            value: ""
      mutate:
        mutateExistingOnPolicyUpdate: true
        patchStrategicMerge:
          metadata:
            labels:
              cost-center: "{{ lookup('v1', 'Namespace', request.namespace).metadata.labels.cost-center }}"
              insights_cost_management_optimizations: "true"
