apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/konflux-ci/notification-service/config/default?ref=637331de6ddf1b60b8135408ce793252edfc02d6

images:
  - name: quay.io/konflux-ci/notification-service
    newName: quay.io/konflux-ci/notification-service
    newTag: 637331de6ddf1b60b8135408ce793252edfc02d6

namespace: notification-controller

patches:
  - path: topic_region_add.yaml
    target:
      name: notification-controller-controller-manager
      kind: Deployment
