apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=a4834e5b480f84fe0fd38fa8d48c65eabe425541

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: a4834e5b480f84fe0fd38fa8d48c65eabe425541

namespace: project-controller
