apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=c68a9b0ba1b8183edc767e9e21a81a8748c76a29

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: c68a9b0ba1b8183edc767e9e21a81a8748c76a29

namespace: project-controller
