apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/project-controller/config/default?ref=3b3052e9eaaa5e7be9377702d4ca1ef1325bbb4c

images:
- name: konflux-project-controller
  newName: quay.io/konflux-ci/project-controller
  newTag: 3b3052e9eaaa5e7be9377702d4ca1ef1325bbb4c

namespace: project-controller
