apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  template:
    spec:
      initContainers:
      - name: cert-manager-package-debian
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
