apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/stonesoup-member-cluster?ref=5e2b25a79b0ec6f242161c5a159e6fad8e85a16f
- ../../openshift-gitops/overlays/staging
- ../../base/external-secrets
- ../../base/monitoring
- authentication

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: 5e2b25a79b0ec6f242161c5a159e6fad8e85a16f

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
