apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: konflux-policies
resources:
- namespace.yaml
- taskruns-cluster-policy.yaml
- restrict-docker-io/
# - cost-management/
- konflux-rbac/
- integration/
- kubearchive/
# Comment out Kueue policies since Kueue is only in ring overlays now
# - kueue/
